=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej01-catalogo.dtd
<!ELEMENT catalogo (libro+)> 
<!ELEMENT libro (id,titulo, autor, anioPublicacion,genero,precio,disponibilidad)> 
<!ELEMENT id (#PCDATA)>
<!ELEMENT titulo (#PCDATA)> 
<!ELEMENT autor (#PCDATA)> 
<!ELEMENT anioPublicacion (#PCDATA)> 
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT disponibilidad (#PCDATA)>

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej01-catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "ej01-catalogo.dtd">
<!-- Nombre de autor: Alfonso Carmona Aguayo  -->
<catalogo>
    <!-- primer libro -->
    <libro>
        <id>001</id>
        <titulo>El Quijote</titulo>
        <autor>Miguel de Cervantes</autor>
        <anioPublicacion>1605</anioPublicacion>
        <genero>Novela</genero>
        <precio moneda="EUR">15.99</precio>
        <disponibilidad>Disponible</disponibilidad>
    </libro>
    <!-- segundo libro -->
    <libro>
        <id>002</id>
        <titulo>Cien Años de Soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <anioPublicacion>1967</anioPublicacion>
        <genero>Realismo mágico</genero>
        <precio moneda="EUR">15.99</precio>
        <disponibilidad>Disponible</disponibilidad>
    </libro>
    <!-- tercer libro -->
    <libro>
        <id>003</id>
        <titulo>1984</titulo>
        <autor>George Orwell</autor>
        <anioPublicacion>1949</anioPublicacion>
        <genero>Distopía</genero>
       <precio moneda="EUR">15.99</precio>
        <disponibilidad>Disponible</disponibilidad>
    </libro>
    <!-- cuarto libro -->
    <libro>
        <id>004</id>
        <titulo>La Odisea</titulo>
        <autor>Homero</autor>
        <anioPublicacion>-800</anioPublicacion>
        <genero>Poema épico</genero>
       <precio moneda="EUR">15.99</precio>
        <disponibilidad>Disponible</disponibilidad>
    </libro>
    <!-- quinto libro -->
    <libro>
        <id>005</id>
        <titulo>Orgullo y Prejuicio</titulo>
        <autor>Jane Austen</autor>
        <anioPublicacion>1813</anioPublicacion>
        <genero>Romance</genero>
        <precio moneda="EUR">15.99</precio>
        <disponibilidad>Disponible</disponibilidad>
    </libro>
</catalogo>
