=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej02-contacto.dtd
<!ELEMENT agenda (contacto+)>
<!ELEMENT contacto (nombre, numero, email, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (ciudad, codigoPostal)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigoPostal (#PCDATA)>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej02-contacto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "ej02-contacto.dtd">
<!-- Nombre de autor: Alfonso Carmona Aguayo  -->
<agenda>
    <!-- primer contacto -->
    <contacto>
        <nombre>Rosario Prieto</nombre>
        <numero>674908254</numero>
        <email>rosarioprieto@gmail.com</email>
         <direccion>
        <ciudad>Malaga</ciudad>
        <codigoPostal>14191</codigoPostal>
         </direccion>
    </contacto>
        
    <!-- segundo contacto -->
    <contacto>
        <nombre>Antonio Perez</nombre>
        <numero>689345125</numero>
        <email>antonioperez@gmail.com</email>
         <direccion>
        <ciudad>Barcelona</ciudad>
        <codigoPostal>14120</codigoPostal>
         </direccion>
    </contacto>
    <!-- tercer contacto -->
    <contacto>
        <nombre>Jesus Rodriguez</nombre>
        <numero>610234580</numero>
        <email>jesusrodriguez@gmail.com</email>
         <direccion>
        <ciudad>Almeria</ciudad>
        <codigoPostal>14100</codigoPostal>
         </direccion>
         </contacto>
    </agenda>
