=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej04-dni.dtd
<!ELEMENT dni (datos)>
<!ELEMENT datos (nombre, apellidos, dni_numero, fecha_nacimiento, nacionalidad, direccion, sexo, fecha_emision, fecha_caducidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni_numero (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT fecha_emision (#PCDATA)>
<!ELEMENT fecha_caducidad (#PCDATA)>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej04-dni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dni SYSTEM "ej04-dni.dtd">
 <dni>
<datos>
    <nombre>Alberto</nombre>
    <apellidos>Conrado Zafra</apellidos>
    <dni_numero>12345678T</dni_numero>
    <fecha_nacimiento>1998-07-15</fecha_nacimiento>
    <nacionalidad>Espa√±ola</nacionalidad>
     <direccion>
        <calle>Calle las Moras</calle>
        <ciudad>Madrid</ciudad>
        <codigo_postal>14100</codigo_postal>
    </direccion>
    <sexo>Hombre</sexo>
    <fecha_emision>2022-02-14</fecha_emision>
    <fecha_caducidad>2034-10-29</fecha_caducidad>
</datos>
</dni>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->
