=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej05-tarjeta.dtd
<!ELEMENT tarjeta (datos)>
<!ELEMENT datos (numeroTarjeta, titular, fecha_vencimiento, tipo_tarjeta, entidad, cvc)>
<!ELEMENT numeroTarjeta (#PCDATA)>
<!ELEMENT titular (#PCDATA)>
<!ELEMENT fecha_vencimiento (#PCDATA)>
<!ELEMENT tipo_tarjeta (#PCDATA)>
<!ELEMENT entidad (#PCDATA)>
<!ELEMENT cvc (#PCDATA)>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej05-tarjeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tarjeta SYSTEM "ej05-tarjeta.dtd">
<tarjeta>
    <datos>
        <numeroTarjeta>654138186548123</numeroTarjeta>
        <titular>Antonio Perez Martin</titular>
        <fecha_vencimiento>2027-07-12</fecha_vencimiento>
        <tipo_tarjeta>Credito</tipo_tarjeta>
        <entidad>Caja sur</entidad>
        <cvc>123</cvc>
    </datos>
</tarjeta>
