=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej07-app.dtd
<!ELEMENT app (informacion, base_datos, configuracion_usuario)>

<!ELEMENT informacion (nombre, version, autor)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

<!ELEMENT base_datos (host, puerto, usuario, contrasena, nombre_base_datos)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT puerto (#PCDATA)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT contrasena (#PCDATA)>
<!ELEMENT nombre_base_datos (#PCDATA)>

<!ELEMENT configuracion_usuario (tema, idioma, preferencias)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT preferencias (notificaciones, autoguardado, fondo_pantalla)>
<!ELEMENT notificaciones (#PCDATA)>
<!ELEMENT autoguardado (#PCDATA)>
<!ELEMENT fondo_pantalla (#PCDATA)>

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej07-app.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuracion SYSTEM "ej07-app.dtd">
<app>
    <informacion>
        <nombre>app fit</nombre>
        <version>1.0</version>
        <autor>Alfonso Carmona</autor>
    </informacion>
    <base_datos>
        <host>localhost</host>
        <puerto>3306</puerto>
        <usuario>admin</usuario>
        <contrasena>1234</contrasena>
        <nombre_base_datos>base de datos free</nombre_base_datos>
    </base_datos>
    <configuracion_usuario>
        <tema>oscuro</tema>
        <idioma>espa√±ol</idioma>
        <preferencias>
            <notificaciones>activadas</notificaciones>
            <autoguardado>desactivado</autoguardado>
            <fondo_pantalla>negro oscuro</fondo_pantalla>
        </preferencias>
    </configuracion_usuario>
</app>
