=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej08-notas.dtd
<!ELEMENT notas (alumno)>
<!ELEMENT alumno (nombre, curso, asignatura+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT asignatura (nombre, notas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT notas (trimestre+)>
<!ELEMENT trimestre (#PCDATA)>
<!ATTLIST trimestre numero CDATA #REQUIRED>

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej08-notas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notas SYSTEM "./ej08-notas.dtd">
<notas>
<alumno>
    <nombre>Antonio Carmona</nombre>
    <curso>1ยบ DAW</curso>
     <asignatura>
    <nombre>Programacion</nombre>
<notas>
 <trimestre numero="1">8.5</trimestre>
 <trimestre numero="2">9.0</trimestre>
 <trimestre numero="3">7.5</trimestre>
 </notas>
 </asignatura>
 <asignatura>
 <nombre>Sistemas Informaticos</nombre>
 <notas>
 <trimestre numero="1">6.5</trimestre>
 <trimestre numero="2">8.0</trimestre>
 <trimestre numero="3">6.0</trimestre>
   </notas>
    </asignatura>
    </alumno>
</notas>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->
