=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej10-estacion.dtd
<!ELEMENT estacion_meteorologica (ubicacion, registro)>
<!ELEMENT ubicacion (ciudad, pais, coordenadas)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT coordenadas (latitud, longitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT registro (fecha, hora, temperatura, humedad, presion, viento, lluvia)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT humedad (#PCDATA)>
<!ELEMENT presion (#PCDATA)>
<!ELEMENT viento (direccion, velocidad)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT lluvia (#PCDATA)>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej10-estacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estacion_meteorologica SYSTEM "ej10-estacion.dtd">
<estacion_meteorologica>
    <ubicacion>
        <ciudad>Madrid</ciudad>
        <pais>Espa√±a</pais>
        <coordenadas>
            <latitud>40.4168</latitud>
            <longitud>-3.7038</longitud>
        </coordenadas>
    </ubicacion>
    <registro>
        <fecha>2025-01-18</fecha>
        <hora>14:30</hora>
        <temperatura>15.2</temperatura>
        <humedad>65</humedad>
        <presion>1015</presion>
        <viento>
            <direccion>Norte</direccion>
            <velocidad>12.5</velocidad>
        </viento>
        <lluvia>0.0</lluvia>
    </registro>
</estacion_meteorologica>
