=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej11-tienda.dtd
<!ELEMENT tienda (producto+)>
<!ELEMENT producto (id, nombre, descripcion, categoria, precio, stock, caracteristicas)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT caracteristicas (caracteristica+)>
<!ELEMENT caracteristica (#PCDATA)>

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej11-tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "ej11-tienda.dtd">
<tienda>
    <producto>
        <id>001</id>
        <nombre>Iphone13</nombre>
        <descripcion>Smartphone con gran rendimiento y cámara de calidad.</descripcion>
        <categoria>Electronica</categoria>
        <precio moneda="EUR">12.00</precio>
        <stock>25</stock>
        <caracteristicas>
            <caracteristica>Pantalla AMOLED de 6.7"</caracteristica>
            <caracteristica>Cámara principal de 108 MP</caracteristica>
            <caracteristica>Batería de 5000 mAh</caracteristica>
        </caracteristicas>
    </producto>
</tienda>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->
