=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej12-libreria.dtd
<!ELEMENT libreria (libro+)>
<!ELEMENT libro (isbn, titulo, autor, categoria, precio, disponibilidad)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT disponibilidad (stock, vendidos)>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT vendidos (#PCDATA)>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->

=== Aca1998/lenguaje2024_alfonso_carmona/Lenguajes2024_Alfonso_Carmona/segundotrimestre/ejercicios/ej12-libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "ej12-libreria.dtd">
<libreria>
    <libro>
        <isbn>978-3-16-148410-0</isbn>
        <titulo>La Celestina</titulo>
        <autor>Fernando Rojas</autor>
        <categoria>Novela Drama</categoria>
        <precio moneda="EUR">29.99</precio>
        <disponibilidad>
            <stock>15</stock>
            <vendidos>120</vendidos>
        </disponibilidad>
    </libro>
    <libro>
        <isbn>978-1-61-729443-3</isbn>
        <titulo>Dracula</titulo>
        <autor>Bram Stoker</autor>
        <categoria>Novela de terror</categoria>
        <precio moneda="USD">39.99</precio>
        <disponibilidad>
            <stock>8</stock>
            <vendidos>50</vendidos>
        </disponibilidad>
    </libro>
</libreria>

<!-- Nombre de autor: Alfonso Carmona Aguayo  -->
